name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # ou qualquer outro branch que você queira monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (se necessário)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # substitua pela sua região

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Instalar Elastic Beanstalk CLI
          pip install awsebcli

          # Inicializar EB CLI
          eb init -p python-3.7 meu-app  # substitua 'meu-app' pelo nome do seu aplicativo
          eb create meu-ambiente        # substitua 'meu-ambiente' pelo nome do seu ambiente
          eb deploy
