name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - Bookstore_development
      - Bookstore_homolog

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to S3
      run: aws s3 cp ./publish s3://my-bucket/${{ github.ref_name }}/ --recursive

    - name: Create Elastic Beanstalk Application Version
      run: |
        VERSION_LABEL=$(date +%Y%m%d%H%M%S)
        ENV_NAME=""
        APP_NAME=""
        
        if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          ENV_NAME="DevelopmentBookstore"
          APP_NAME="Boostore"
        elif [ "${{ github.ref }}" == "refs/heads/homolog" ]; then
          ENV_NAME="HomologBookstore"
          APP_NAME="Bookstore"
        fi
        
        aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket="my-bucket",S3Key="${{ github.ref_name }}/publish.zip"
        aws elasticbeanstalk update-environment --environment-name $ENV_NAME --version-label $VERSION_LABEL
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
