name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - bookstore_development
      - bookstore_homolog
      - TestDeploy  # Adicione isso se quiser testar com o branch testDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Publish .NET Core app
      run: dotnet publish -c Release -o ./publish

    - name: Zip published files
      run: zip -r Bookstore.zip ./publish/*

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        if [ "${{ github.ref }}" ==
