// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace bookstore.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bookstore.models.Books", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("bookstore.models.Books", b =>
                {
                    b.OwnsOne("bookstore.models.CoverBook", "Capa", b1 =>
                        {
                            b1.Property<int>("BooksID")
                                .HasColumnType("int");

                            b1.Property<string>("Base64")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Base64");

                            b1.Property<string>("ImagemNome")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("ImagemNome");

                            b1.Property<decimal>("ImagemTamanho")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("ImagemTamanho");

                            b1.Property<string>("ImagemTipo")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("ImagemTipo");

                            b1.HasKey("BooksID");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BooksID");
                        });

                    b.Navigation("Capa")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
