name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - Bookstore_development  # Verifique se este é o branch correto

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build .NET application
        run: |
          dotnet build
          dotnet publish -c Release -o publish

      - name: Upload to S3
        run: |
          aws s3 cp publish/ s3://s3-dan-user/publish.zip --recursive

      - name: Create new application version
        id: create_version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Bookstore \
            --version-label ${{ github.run_number }} \
            --source-bundle S3Bucket=s3-dan-user,S3Key=publish.zip \
            --region us-east-1

      - name: Update Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
            --application-name Bookstore \
            --environment-name DevelopmentBookstore \
            --version-label ${{ github.run_number }} \
            --region us-east-1
