name: Deploy to EC2

on:
  push:
    branches:
      - Bookstore_development  # substitua pela branch que você está usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # substitua pela versão do .NET que você está usando

    - name: Publish .NET application
      run: dotnet publish -c Release -o out

    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/parChavesLinux.pem
        chmod 400 ~/.ssh/parChavesLinux.pem

    - name: Upload to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/parChavesLinux.pem -r out/* ec2-user@ec2-54-234-30-239.compute-1.amazonaws.com:/var/www/myapp
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/parChavesLinux.pem ec2-user@ec2-54-234-30-239.compute-1.amazonaws.com 'sudo systemctl restart myapp'
