name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - Bookstore_development
      - Bookstore_homolog

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Package application
      run: |
        zip -r Public.zip .

    - name: Upload to S3
      run: |
        aws s3 cp Public.zip s3://s3-dan-user/Public.zip

    - name: Create application version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name Bookstore_DEVELOPMENT \
          --version-label ${{ github.sha }} \
          --source-bundle S3Bucket="s3-dan-user",S3Key="Public.zip"

    - name: Update Elastic Beanstalk environment
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name DevelopmentBookstore \
          --version-label ${{ github.sha }}

    - name: Confirm update
      run: |
        aws elasticbeanstalk describe-environments \
          --environment-names DevelopmentBookstore
