name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # ou qualquer outro branch que você queira monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Defina a versão do .NET que você está usando

      - name: Restore dependencies
        run: dotnet restore
        working-directory: bookstore  # Ajuste para o diretório onde está sua aplicação .NET

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: bookstore  # Ajuste para o diretório onde está sua aplicação .NET

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: bookstore  # Ajuste para o diretório onde está sua aplicação .NET

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # substitua pela sua região

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Instalando Elastic Beanstalk CLI"
          pip install awsebcli
          
          echo "Mudando para o diretório bookstore/publish"
          cd bookstore/publish
          
          echo "Inicializando EB CLI"
          eb init -p python-3.7 bbfDOTNET --region us-east-1  # Ajuste conforme necessário
          
          echo "Verificando se o ambiente existe"
          if eb status meu-ambiente; then
            echo "Ambiente já existe"
          else
            echo "Criando o ambiente"
            eb create meu-ambiente --region us-east-1  # Certifique-se de que o nome do ambiente e a região estejam corretos
          fi
          
          echo "Realizando o deploy"
          eb deploy
