name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - Bookstore_development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build .NET application
        run: |
          dotnet build
          dotnet publish -c Release -o publish

      - name: Zip the publish directory
        run: |
          zip -r publish.zip publish

      - name: Check AWS CLI version
        run: aws --version

      - name: Verify S3 Bucket Access
        run: aws s3 ls s3://s3-dan-user/

      - name: Upload to S3
        run: |
          aws s3 cp publish.zip s3://s3-dan-user/publish.zip --debug

      - name: Create new application version
        id: create_version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Bookstore \
            --version-label ${{ github.run_number }} \
            --source-bundle S3Bucket=s3-dan-user,S3Key=publish.zip \
            --region us-east-1

      - name: Update Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
            --application-name Bookstore \
            --environment-name DevelopmentBookstore \
            --version-label ${{ github.run_number }} \
            --region us-east-1
