name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - TestDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Zip the publish directory
      run: zip -r publish.zip ./publish

    - name: Upload to S3
      run: aws s3 cp publish.zip s3://elasticbeanstalk-us-east-1-308476907918/publish.zip --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Create Application Version
      run: |
        aws elasticbeanstalk create-application-version --application-name Bookstore --version-label ${{ github.run_number }} --source-bundle S3Bucket=elasticbeanstalk-us-east-1-308476907918,S3Key=publish.zip --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Wait for Application Version to be Processed
      run: sleep 60  # Ajuste o tempo de espera conforme necessário

    - name: Deploy to Elastic Beanstalk - Development
      run: |
        aws elasticbeanstalk update-environment --application-name Bookstore --environment-name DevelopmentBookstore --version-label ${{ github.run_number }} --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Elastic Beanstalk - Homologation
      run: |
        aws elasticbeanstalk update-environment --application-name Bookstore --environment-name HomologBookstore --version-label ${{ github.run_number }} --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
