name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # ou qualquer outro branch que você queira monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para a versão v3

      - name: Set up Node.js (se necessário)
        uses: actions/setup-node@v3  # Atualizado para a versão v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: bookstore  # Ajuste para o diretório onde está sua aplicação

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Certifique-se de usar v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # substitua pela sua região

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Instalar Elastic Beanstalk CLI
          pip install awsebcli

          # Navegar para o diretório onde está a aplicação
          cd bookstore

          # Inicializar EB CLI com o nome do aplicativo no Elastic Beanstalk
          eb init -p python-3.7 bbfDOTNET  # substitua 'bbfDOTNET' pelo nome do seu aplicativo no Elastic Beanstalk

          # Criar o ambiente no Elastic Beanstalk, se ainda não estiver criado
          eb create meu-ambiente  # substitua 'meu-ambiente' pelo nome do seu ambiente no Elastic Beanstalk

          # Deploy para o Elastic Beanstalk
          eb deploy
